apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-api-ingress
  namespace: links
  labels:
    app.kubernetes.io/name: proxy-api-ingress

spec:
  rules:
  - host: class.hypertheory-labs.com
    https:
      paths:
      - pathType: Prefix
        path: "/guacamole"
        backend:
          service:
            name: apache-guacamole
            port: 
              number: 443
